In [2]:
#Dependencies
import pandas as pd

#import csvs
file15 = "../Resources/Happy15.csv"
file16 = "../Resources/Happy16.csv"
file17 = "../Resources/Happy17.csv"
file18 = "../Resources/Happy18.csv"
file19 = "../Resources/Happy19.csv"

#
df15 = pd.read_csv(file15)
df16 = pd.read_csv(file16)
df17 = pd.read_csv(file17)
df18 = pd.read_csv(file18)
df19 = pd.read_csv(file19)

In [5]:
# Add a year column
df15['Year'] = 2015
df16['Year'] = 2016
df17['Year'] = 2017
df18['Year'] = 2018
df19['Year'] = 2019

In [30]:
#rename columns
df17.rename(columns={'Happiness.Rank': 'Happiness Rank', 'Happiness.Score': 'Happiness Score',
                     'Economy..GDP.per.Capita.': 'Economy (GDP per Capita)',
                     'Health..Life.Expectancy.': 'Health (Life Expectancy)',
                     'Trust..Government.Corruption.':'Trust (Government Corruption)',
                     'Dystopia.Residual': 'Dystopia Residual'})
df18.rename(columns={'Overall rank': 'Happiness Rank', 'Country or region': 'Country', 'Score': 'Happiness Score',
                     'GDP per capita': 'Economy (GDP per capita)', 'Social support': 'Family',
                     'Healthy life expectancy': 'Health (Life Expectancy)', 'Freedom to make life choices':'Freedom',
                     'Perceptions of corruption': 'Trust (Government Corruption)'})
df19.rename(columns={'Overall rank': 'Happiness Rank', 'Country or region': 'Country', 'Score': 'Happiness Score',
                     'GDP per capita': 'Economy (GDP per capita)', 'Social support': 'Family',
                     'Healthy life expectancy': 'Health (Life Expectancy)', 'Freedom to make life choices':'Freedom',
                     'Perceptions of corruption': 'Trust (Government Corruption)'})

,Happiness Rank,Country,Happiness Score,Economy (GDP per capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Year
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019
...,...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411,2019
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147,2019
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025,2019
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035,2019
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091,2019

In [31]:
#clean columns
df15clean = df15[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year']]
df16clean = df16[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year']]
df17clean = df17[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year']]
df18clean = df18[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year']]
df19clean = df19[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year']]

KeyError: "['Health (Life Expectancy)', 'Trust (Government Corruption)', 'Dystopia Residual', 'Happiness Score', 'Economy (GDP per Capita)', 'Happiness Rank'] not in index"

In [27]:
df17.columns

Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual', 'Year'],
      dtype='object')

In [11]:
#Concat all dfs
df = pd.concat([df15, df16, df17, df18, df19])
df.head(20)

C:\Users\slapp\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Country,Country or region,Dystopia Residual,Dystopia.Residual,Economy (GDP per Capita),Economy..GDP.per.Capita.,Family,Freedom,Freedom to make life choices,GDP per capita,...,Region,Score,Social support,Standard Error,Trust (Government Corruption),Trust..Government.Corruption.,Upper Confidence Interval,Whisker.high,Whisker.low,Year
0,Switzerland,NaN,2.51738,NaN,1.39651,NaN,1.34951,0.66557,NaN,NaN,...,Western Europe,NaN,NaN,0.03411,0.41978,NaN,NaN,NaN,NaN,2015
1,Iceland,NaN,2.70201,NaN,1.30232,NaN,1.40223,0.62877,NaN,NaN,...,Western Europe,NaN,NaN,0.04884,0.14145,NaN,NaN,NaN,NaN,2015
2,Denmark,NaN,2.49204,NaN,1.32548,NaN,1.36058,0.64938,NaN,NaN,...,Western Europe,NaN,NaN,0.03328,0.48357,NaN,NaN,NaN,NaN,2015
3,Norway,NaN,2.46531,NaN,1.45900,NaN,1.33095,0.66973,NaN,NaN,...,Western Europe,NaN,NaN,0.03880,0.36503,NaN,NaN,NaN,NaN,2015
4,Canada,NaN,2.45176,NaN,1.32629,NaN,1.32261,0.63297,NaN,NaN,...,North America,NaN,NaN,0.03553,0.32957,NaN,NaN,NaN,NaN,2015
5,Finland,NaN,2.61955,NaN,1.29025,NaN,1.31826,0.64169,NaN,NaN,...,Western Europe,NaN,NaN,0.03140,0.41372,NaN,NaN,NaN,NaN,2015
6,Netherlands,NaN,2.46570,NaN,1.32944,NaN,1.28017,0.61576,NaN,NaN,...,Western Europe,NaN,NaN,0.02799,0.31814,NaN,NaN,NaN,NaN,2015
7,Sweden,NaN,2.37119,NaN,1.33171,NaN,1.28907,0.65980,NaN,NaN,...,Western Europe,NaN,NaN,0.03157,0.43844,NaN,NaN,NaN,NaN,2015
8,New Zealand,NaN,2.26425,NaN,1.25018,NaN,1.31967,0.63938,NaN,NaN,...,Australia and New Zealand,NaN,NaN,0.03371,0.42922,NaN,NaN,NaN,NaN,2015
9,Australia,NaN,2.26646,NaN,1.33358,NaN,1.30923,0.65124,NaN,NaN,...,Australia and New Zealand,NaN,NaN,0.04083,0.35637,NaN,NaN,NaN,NaN,2015
10,Israel,NaN,3.08854,NaN,1.22857,NaN,1.22393,0.41319,NaN,NaN,...,Middle East and Northern Africa,NaN,NaN,0.03470,0.07785,NaN,NaN,NaN,NaN,2015
11,Costa Rica,NaN,3.17728,NaN,0.95578,NaN,1.23788,0.63376,NaN,NaN,...,Latin America and Caribbean,NaN,NaN,0.04454,0.10583,NaN,NaN,NaN,NaN,2015
12,Austria,NaN,2.53320,NaN,1.33723,NaN,1.29704,0.62433,NaN,NaN,...,Western Europe,NaN,NaN,0.03751,0.18676,NaN,NaN,NaN,NaN,2015
13,Mexico,NaN,3.60214,NaN,1.02054,NaN,0.91451,0.48181,NaN,NaN,...,Latin America and Caribbean,NaN,NaN,0.04176,0.21312,NaN,NaN,NaN,NaN,2015
14,United States,NaN,2.51011,NaN,1.39451,NaN,1.24711,0.54604,NaN,NaN,...,North America,NaN,NaN,0.03839,0.15890,NaN,NaN,NaN,NaN,2015
15,Brazil,NaN,3.26001,NaN,0.98124,NaN,1.23287,0.49049,NaN,NaN,...,Latin America and Caribbean,NaN,NaN,0.04076,0.17521,NaN,NaN,NaN,NaN,2015
16,Luxembourg,NaN,1.96961,NaN,1.56391,NaN,1.21963,0.61583,NaN,NaN,...,Western Europe,NaN,NaN,0.03499,0.37798,NaN,NaN,NaN,NaN,2015
17,Ireland,NaN,1.97570,NaN,1.33596,NaN,1.36948,0.61777,NaN,NaN,...,Western Europe,NaN,NaN,0.03676,0.28703,NaN,NaN,NaN,NaN,2015
18,Belgium,NaN,2.41484,NaN,1.30782,NaN,1.28566,0.58450,NaN,NaN,...,Western Europe,NaN,NaN,0.03595,0.22540,NaN,NaN,NaN,NaN,2015
19,United Arab Emirates,NaN,2.24743,NaN,1.42727,NaN,1.12575,0.64157,NaN,NaN,...,Middle East and Northern Africa,NaN,NaN,0.03729,0.38583,NaN,NaN,NaN,NaN,2015

In [12]:
print(df15.columns)
print(df16.columns)
print(df17.columns)
print(df18.columns)
print(df19.columns)

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual', 'Year'],
      dtype='object')
Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual', 'Year'],
      dtype='object')
Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual', 'Year'],
      dtype='object')
Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Year'],
      dtype='object')
Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Year'],
      dtype='object')

In [15]:
cleandf = pd.DataFrame[df['Country'], df['Region']]
cleandf.head()

TypeError: 'type' object is not subscriptable